from abc import abstractmethod

import numpy as np

from .s2_base import S2Samples


class ThetasFromIndex(S2Samples):
    r"""
    Mixin for sampling schemes that generate :math:`\theta` coordinates from indices.

    Class provides the `thetas` property, assuming that the coordinates can be generated
    from a `numpy.arange(0, self.n_thetas)` array. The :math:`\theta` coordinates are then
    generated by the abstract method `_theta_index_to_value`; that is,
    `self.thetas[t] = self._theta_index_to_value(t)`.
    """

    @abstractmethod
    def _theta_index_to_value(self, theta_index: np.ndarray) -> np.ndarray:
        r"""
        Convert index to :math:`\theta` angle for sampling scheme.

        Args:
            theta_index (np.ndarray): :math:`\theta` indexes.

        Returns:
            np.ndarray: :math:`\theta` sample(s) for given sampling scheme.

        """

    @property
    def thetas(self) -> np.ndarray:
        return self._theta_index_to_value(np.arange(0, self.n_theta)).astype(np.float64)
